Repository Activiti/example-cloud-connector, pull requests merged in 2018-12, with the labels that each got.

#30 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.96
  pom.xml
Labels: in progress, updatebot

#31 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.97
  pom.xml
Labels: updatebot

#34 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.100
  pom.xml
Labels: in progress, updatebot

#35 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.104
  pom.xml
Labels: in progress, updatebot

#36 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.105
  pom.xml
Labels: in progress, updatebot

#32 pipelines configuration
  .mergify.yml
  .updatebot.yml
  Jenkinsfile
  charts/activiti-cloud-connector/.helmignore
  charts/activiti-cloud-connector/Chart.yaml
  charts/activiti-cloud-connector/Makefile
  charts/activiti-cloud-connector/README.md
  charts/activiti-cloud-connector/templates/NOTES.txt
  charts/activiti-cloud-connector/templates/_helpers.tpl
  charts/activiti-cloud-connector/templates/deployment.yaml
  charts/activiti-cloud-connector/templates/service.yaml
  charts/activiti-cloud-connector/values.yaml
  maven-dind.yaml
  pom.xml
  skaffold.yaml
Labels: in progress

#38 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.108
  pom.xml
Labels: in progress, updatebot

#40 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.109
  pom.xml
Labels: updatebot

#41 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.110
  pom.xml
Labels: updatebot

#43 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.113
  pom.xml
Labels: updatebot

#44 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.114
  pom.xml
Labels: updatebot

#45 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.115
  pom.xml
Labels: updatebot

#46 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.116
  pom.xml
Labels: updatebot

#47 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.117
  pom.xml
Labels: updatebot

#48 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.118
  pom.xml
Labels: updatebot

#49 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.119
  pom.xml
Labels: updatebot

#24 handling of json vars and custom pojos
  src/main/java/org/activiti/cloud/examples/connectors/CustomPojo.java
  src/main/java/org/activiti/cloud/examples/connectors/ExampleConnector.java
  src/test/java/org/activiti/cloud/examples/CloudConnectorAppIT.java
Labels: in progress

#50 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.120
  pom.xml
Labels: updatebot

#51 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.121
  pom.xml
Labels: updatebot

#52 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.122
  pom.xml
Labels: updatebot

#53 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.123
  pom.xml
Labels: updatebot

#54 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.124
  pom.xml
Labels: updatebot

#55 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.125
  pom.xml
Labels: updatebot

#56 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.126
  pom.xml
Labels: updatebot

#57 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.127
  pom.xml
Labels: updatebot

#58 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.128
  pom.xml
Labels: updatebot

#60 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.130
  pom.xml
Labels: updatebot

#61 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.131
  pom.xml
Labels: updatebot

#62 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.132
  pom.xml
Labels: updatebot

#63 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.133
  pom.xml
Labels: updatebot
