Repository Activiti/example-cloud-connector, pull requests merged in 2018-11, with the labels that each got.

#18 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.75
  pom.xml
Labels: updatebot

#22 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.77
  pom.xml
Labels: updatebot

#23 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.81
  pom.xml
Labels: in progress, updatebot

#25 apply cloud dep upgrade to master
  pom.xml
Labels: in progress

#28 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.91
  pom.xml
Labels: in progress, updatebot

#29 take out bean overriding
  src/main/resources/application.properties
  src/test/resources/application-test.properties
Labels: in progress
